# Resources/config/services.yml
services:

    webeweb.bundle.adminbsbbundle.provider.manager:
        class:     WBW\Bundle\AdminBSBBundle\Provider\ProvidersManager
        arguments: ["@twig"]
        calls:
            - [setApplicationProvider, ["@?webeweb.bundle.adminbsbbundle.provider.application"]]
            - [setBreadcrumbsProvider, ["@?webeweb.bundle.adminbsbbundle.provider.breadcrumbs"]]
            - [setDropDownHookProvider, ["@?webeweb.bundle.adminbsbbundle.provider.drop_down_hook"]]
            - [setDropDownNotificationsProvider, ["@?webeweb.bundle.adminbsbbundle.provider.drop_down_notifications"]]
            - [setDropDownTasksProvider, ["@?webeweb.bundle.adminbsbbundle.provider.drop_down_tasks"]]
            - [setFooterProvider, ["@?webeweb.bundle.adminbsbbundle.provider.footer"]]
            - [setNavigationProvider, ["@?webeweb.bundle.adminbsbbundle.provider.navigation"]]
            - [setSearchProvider, ["@?webeweb.bundle.adminbsbbundle.provider.search"]]
            - [setUserInfoProvider, ["@?webeweb.bundle.adminbsbbundle.provider.user_info"]]

    webeweb.bundle.adminbsbbundle.twig.extension.code.basicblock:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Code\BasicBlockCodeTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.code.inline:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Code\InlineCodeTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.code.sampleoutput:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Code\SampleOutputCodeTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.code.userinput:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Code\UserInputCodeTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.code.variable:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Code\VariableCodeTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.form.checkbox:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Form\CheckboxFormTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.form.radiobutton:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Form\RadioButtonFormTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.form.switchbutton:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Form\SwitchButtonFormTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.grid.grid:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Grid\GridTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.deleted:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\DeletedTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.heading:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\HeadingTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.inserted:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\InsertedTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.italic:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\ItalicTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.marked:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\MarkedTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.small:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\SmallTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.strikethrough:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\StrikeThroughTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.strong:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\StrongTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.typography.underlined:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\UnderlinedTypographyTwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.alert:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\AlertUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.badge:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\BadgeUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.button:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ButtonUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.color:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ColorUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.icon:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\IconUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.label:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\LabelUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.modal:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ModalUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.preloader:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\PreloaderUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.ui.progressbar:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ProgressBarUITwigExtension
        tags:
            - { name: twig.extension }

    webeweb.bundle.adminbsbbundle.twig.extension.widget.card:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Widget\CardWidgetTwigExtension
        tags:
            - { name: twig.extension }
