# Resources/config/services.yml
services:

    webeweb.adminbsbbundle.twig.extension.form.checkbox:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Form\CheckboxFormTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.form.radiobutton:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Form\RadioButtonFormTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.form.switchbutton:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Form\SwitchButtonFormTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.menu.multilevelmenu:
        class:     WBW\Bundle\AdminBSBBundle\Twig\Extension\Menu\MultiLevelMenuTwigExtension
        arguments: ["@translator"]
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.typography.italic:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\ItalicTypographyTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.typography.overlined:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\OverlinedTypographyTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.typography.strikethrough:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\StrikethroughTypographyTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.typography.underlined:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Typography\UnderlinedTypographyTwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.badge:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\BadgeUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.button:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ButtonUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.color:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ColorUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.icon:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\IconUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.modal:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ModalUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.preloader:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\PreloaderUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.ui.progressbar:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\UI\ProgressBarUITwigExtension
        tags:
            - { name: "twig.extension" }

    webeweb.adminbsbbundle.twig.extension.widget.card:
        class: WBW\Bundle\AdminBSBBundle\Twig\Extension\Widget\CardWidgetTwigExtension
        tags:
            - { name: "twig.extension" }
